"""
网站定义 - 高低压成套设备行业招标信息源

本文件是网站源配置的单一事实来源（Single Source of Truth）。
所有网站定义集中在此管理，包括：
1. 分类信息
2. 基础属性（名称、URL、爬虫类型）
3. 默认独立配置（可覆盖全局）

GUI 和爬虫层均从此文件导入网站定义，禁止在 gui.py 中硬编码。
"""

from typing import Dict, List, Any, Optional


# =============================================================================
# 分类定义
# =============================================================================

SITE_CATEGORIES: Dict[str, str] = {
    "通用招标平台": "覆盖面广，优先级高",
    "电网公司": "配电侧核心客户",
    "电力行业平台": "行业垂直信息",
    "发电集团": "电厂配电设备需求",
    "工程总包": "项目含配电设备",
    "央企": "中央直属企业电子采购平台",
    "建筑企业": "建筑施工企业招标采购平台",
    "钢铁企业": "钢铁企业采购电商平台",
    "公共资源平台": "政府公共资源交易服务平台",
    "化工企业": "化工企业采购平台",
    "地产企业": "房地产开发商招采平台",
    "能源/石油": "石油石化企业采购平台",
    "能源/煤矿": "煤炭矿业企业采购平台",
    "第三方平台": "第三方招投标信息服务平台",
    "制造业": "制造业企业采购平台",
}


# =============================================================================
# 网站定义（单一事实来源）
# =============================================================================

SITES: Dict[str, Dict[str, Any]] = {
    # === 专用爬虫支持的网站 ===
    "ccgp": {
        "name": "中国政府采购网",
        "url": "http://www.ccgp.gov.cn",
        "category": "通用招标平台",
        "crawler_type": "builtin",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "chinabidding": {
        "name": "中国采购与招标网",
        "url": "https://www.chinabidding.cn/",
        "category": "通用招标平台",
        "crawler_type": "builtin",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "ebnew": {
        "name": "必联网（国义招标）",
        "url": "http://www.ebnew.com",
        "category": "通用招标平台",
        "crawler_type": "builtin",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "plap": {
        "name": "军队采购网",
        "url": "http://www.plap.cn",
        "category": "通用招标平台",
        "crawler_type": "builtin",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },

    # === 通用招标平台 ===
    "chinabiddingcc": {
        "name": "中国采购招标网",
        "url": "http://www.chinabidding.cc/",
        "category": "通用招标平台",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "chinazbcg": {
        "name": "中国招投标信息网",
        "url": "http://www.chinazbcg.com",
        "category": "通用招标平台",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "ebidding": {
        "name": "国义招标",
        "url": "http://www.ebidding.com/portal/",
        "category": "通用招标平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "zjycgzx": {
        "name": "浙江云采购中心",
        "url": "https://www.zjycgzx.com",
        "category": "通用招标平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },

    # === 电网公司 ===
    "sgcc": {
        "name": "国家电网电子商务平台",
        "url": "https://ecp.sgcc.com.cn/",
        "category": "电网公司",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": 45,
        "max_retries": 5,
        "request_delay": None,
        "headers": None,
        "use_selenium": True,
    },
    "csg": {
        "name": "中国南方电网供应链服务平台",
        "url": "http://www.bidding.csg.cn/",
        "category": "电网公司",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": 45,
        "max_retries": 5,
        "request_delay": None,
        "headers": None,
        "use_selenium": True,
    },
    "sgccetp": {
        "name": "国网电子商务平台电工交易专区",
        "url": "https://sgccetp.com.cn/",
        "category": "电网公司",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },

    # === 电力行业平台 ===
    "dlzb": {
        "name": "中国电力招标网",
        "url": "http://www.dlzb.com/",
        "category": "电力行业平台",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cpeinet": {
        "name": "中国电力设备信息网",
        "url": "http://www.cpeinet.com.cn/",
        "category": "电力行业平台",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },

    # === 发电集团 ===
    "gdtzb": {
        "name": "国电投招标网",
        "url": "http://www.gdtzb.com",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "chng": {
        "name": "华能集团电子商务平台",
        "url": "http://ec.chng.com.cn/ecmall/",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "chdtp": {
        "name": "中国华电电子商务平台",
        "url": "http://www.chdtp.com/",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cdt": {
        "name": "中国大唐电子商务平台",
        "url": "http://www.cdt-ec.com/",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "neep": {
        "name": "国家能源e购",
        "url": "https://www.neep.shop/",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "ceic": {
        "name": "国家能源集团生态协作平台",
        "url": "https://cooperation.ceic.com/",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "crpower": {
        "name": "华润电力",
        "url": "https://b2b.crpower.com.cn",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cgnpc": {
        "name": "中广核电子商务平台",
        "url": "https://ecp.cgnpc.com.cn",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "dongfang": {
        "name": "东方电气",
        "url": "http://nsrm.dongfang.com/",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "ctg": {
        "name": "中国三峡电子采购平台",
        "url": "https://eps.ctg.com.cn/",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "sdicc": {
        "name": "国投集团电子采购平台",
        "url": "https://www.sdicc.com.cn/",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "powerbeijing": {
        "name": "北京京能电子商务平台",
        "url": "http://www.powerbeijing-ec.com",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "hghn": {
        "name": "华光环能数字化采购管理平台",
        "url": "https://hgcg.hghngroup.com/",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cecep": {
        "name": "中国节能环保电子采购平台",
        "url": "http://www.ebidding.cecep.cn/",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "gdg": {
        "name": "广州发展集团电子采购平台",
        "url": "https://eps.gdg.com.cn/",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },

    # === 工程总包 ===
    "powerchina": {
        "name": "中国电建采购电子商务平台",
        "url": "http://ec.powerchina.cn",
        "category": "工程总包",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "powerchina_bid": {
        "name": "中国电建采购招标数智化平台",
        "url": "https://bid.powerchina.cn/bidweb/",
        "category": "工程总包",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "powerchina_ec": {
        "name": "中国电建设备物资集中采购平台",
        "url": "https://ec.powerchina.cn/",
        "category": "工程总包",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "powerchina_scm": {
        "name": "中国电建供应链云服务平台",
        "url": "https://scm.powerchina.cn/",
        "category": "工程总包",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "ceec": {
        "name": "中国能建电子采购平台",
        "url": "https://ec.ceec.net.cn/",
        "category": "工程总包",
        "crawler_type": "custom",
        "enabled_by_default": True,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "crc": {
        "name": "华润集团守正电子招标采购平台",
        "url": "https://szecp.crc.com.cn/",
        "category": "工程总包",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },

    # === 央企 ===
    "minmetals": {
        "name": "中国五矿集团有限公司采购电子商务平台",
        "url": "https://ec.minmetals.com.cn/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "ccccltd": {
        "name": "中交集团供应链管理信息系统",
        "url": "http://ec.ccccltd.cn/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },

    # === 建筑企业 ===
    "yzw": {
        "name": "云筑网（中建集团）",
        "url": "https://mall.yzw.cn/",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },

    # === 钢铁企业 ===
    "rizhaosteel": {
        "name": "日钢采购电商平台",
        "url": "https://ep.rizhaosteel.com/",
        "category": "钢铁企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "obei": {
        "name": "欧贝商城（宝武集团）",
        "url": "https://www.obei.com.cn/obei-web-ec/OP/index.html",
        "category": "钢铁企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },

    # === 公共资源平台 ===
    "xaprtc": {
        "name": "雄安新区公共资源交易服务平台",
        "url": "https://www.xaprtc.com/",
        "category": "公共资源平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    # === 新增重点平台（来自飞书表格） ===
    "epec": {
        "name": "易派克（中国石化）",
        "url": "https://mall.epec.com/ecmall/static/homePage.do",
        "category": "能源/石油",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "csemc": {
        "name": "中国船舶物资采购电子商务平台",
        "url": "http://www.ebuy.csemc.com/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "hnjgcg": {
        "name": "湖南建工集团集中采购履约平台",
        "url": "http://tb.hnjgcg.com/",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "tianyiholdings": {
        "name": "天一建设招采平台",
        "url": "https://zcpt.tianyiholdings.com",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cebpubservice": {
        "name": "中国招标投标公共服务平台",
        "url": "http://bulletin.cebpubservice.com/",
        "category": "通用招标平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "sunac": {
        "name": "融创服务供应商协同平台",
        "url": "http://wyxtsrm.sunac.com.cn",
        "category": "地产企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "chinaoct": {
        "name": "华侨城电子招采平台",
        "url": "https://octdzzc.chinaoct.com/",
        "category": "地产企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "webbiao": {
        "name": "中采智信网",
        "url": "http://webbiao.com",
        "category": "第三方平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cnecc": {
        "name": "中国核工业建设股份有限公司集中采购管理系统",
        "url": "http://gys.cnecc.com",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "yzscg": {
        "name": "上海建工电子商务平台",
        "url": "http://www.yzscg.cn/",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "mycaigou": {
        "name": "明源云采购",
        "url": "https://www.mycaigou.com/",
        "category": "第三方平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "zhaobiao_cn": {
        "name": "中国招标网",
        "url": "http://www.zhaobiao.cn",
        "category": "第三方平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "rfchina_bid": {
        "name": "富力集团招投标平台",
        "url": "https://bid.rfchina.com",
        "category": "地产企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "alibaba1688": {
        "name": "1688采购平台",
        "url": "https://go.1688.com/",
        "category": "第三方平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "heyime": {
        "name": "交建合一一站式服务平台",
        "url": "https://tender.heyime.com/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "e2biz": {
        "name": "通用半导体公司在公共电子商务平台（易拓必盛）",
        "url": "http://www.e2biz.com.cn",
        "category": "制造业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "ansteel": {
        "name": "鞍钢集团供应商客户信息平台",
        "url": "http://bid.ansteelscm.com/",
        "category": "钢铁企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "coli688": {
        "name": "中海地产供应商门户",
        "url": "https://hzs.coli688.com",
        "category": "地产企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "sanyou": {
        "name": "唐山三友集团有限公司",
        "url": "http://www.sanyou-group.com.cn/",
        "category": "化工企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "jgjt": {
        "name": "酒钢集团电子交易平台",
        "url": "http://47.110.33.156:8082/",
        "category": "钢铁企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "xinyu": {
        "name": "鑫裕集团",
        "url": "https://rrd4dcdan0.jiandaoyun.com/",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "zttp": {
        "name": "中天控股数字化采购平台",
        "url": "http://mall.zttp.net",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "shansteel": {
        "name": "山钢集团",
        "url": "http://bams.shansteelgroup.com/",
        "category": "钢铁企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "crecgec": {
        "name": "中国中铁采购电子商务平台",
        "url": "https://www.crecgec.com/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "longdaoyun": {
        "name": "隆道平台",
        "url": "https://www.longdaoyun.com/",
        "category": "第三方平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "pinggao": {
        "name": "平高集团供应链管控平台",
        "url": "http://123.163.50.152:30036/",
        "category": "制造业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cetceg": {
        "name": "中电科电子采购平台",
        "url": "http://www.cetceg.com/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "bohuayicai": {
        "name": "渤化易采平台",
        "url": "http://www.bohuayicai.cn/",
        "category": "化工企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cnpcbidding": {
        "name": "中国石油电子招标投标平台",
        "url": "https://ebidmanage.cnpcbidding.com/",
        "category": "能源/石油",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "rfchina_srm": {
        "name": "富力云采",
        "url": "https://srm.rfchina.com/",
        "category": "地产企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "chalieco": {
        "name": "中铝国际电子采购交易平台",
        "url": "http://ec.chalieco.com:5835/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "guangnajituan": {
        "name": "内蒙古广纳集团阳光招采平台",
        "url": "http://zc.guangnajituan.com:2080/",
        "category": "能源/煤矿",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "chinacoal": {
        "name": "中煤易购",
        "url": "http://ego.chinacoal.com/",
        "category": "能源/煤矿",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "tjconstruct": {
        "name": "天津建设工程信息网",
        "url": "http://www.tjconstruct.cn/",
        "category": "公共资源平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "lczc": {
        "name": "绿城中国阳光招采平台",
        "url": "https://lczc.gtcloud.cn/",
        "category": "地产企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "hbisscm": {
        "name": "河钢集团有限公司",
        "url": "http://www.hbisscm.com/",
        "category": "钢铁企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "chnenergybidding": {
        "name": "国家能源招标网",
        "url": "http://www.chnenergybidding.com.cn/",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "crrcgo": {
        "name": "中车供应链管理电子采购平台",
        "url": "http://www.crrcgo.cc/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "bcactc": {
        "name": "多功能平台共享",
        "url": "http://dhygx.bcactc.com/",
        "category": "公共资源平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cncecyc": {
        "name": "中国化学电子招标投标平台",
        "url": "https://bid.cncecyc.com/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "espic": {
        "name": "国家电投电子商务平台",
        "url": "https://ebid.espic.com.cn",
        "category": "发电集团",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "nmgztb": {
        "name": "内蒙古招标投标公共服务平台",
        "url": "http://zbgg.nmgztb.com.cn/",
        "category": "公共资源平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "hhnycg": {
        "name": "淮南矿业集团电子采购平台",
        "url": "http://hhnycg.com/",
        "category": "能源/煤矿",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cnooc": {
        "name": "中国海洋石油集团有限公司采办业务管理与交易系统",
        "url": "https://buy.cnooc.com.cn/",
        "category": "能源/石油",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "rcc": {
        "name": "RCC",
        "url": "https://www.rccchina.com/",
        "category": "第三方平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "crccep": {
        "name": "铁建云彩网",
        "url": "https://www.crccep.com/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "zgsgycw": {
        "name": "威匡/施工云采网",
        "url": "http://www.zgsgycw.com/",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "zgsgycw2": {
        "name": "鸿宝/施工云采网",
        "url": "http://www.zgsgycw.com/",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "jinshuiyuncai": {
        "name": "津水云采网",
        "url": "https://www.jinshuiyuncai.com/",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "sec": {
        "name": "深圳能源",
        "url": "https://zb.sec.com.cn/",
        "category": "能源/石油",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cofco": {
        "name": "中粮E采",
        "url": "https://ecai.cofco.com/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "sinochemitc": {
        "name": "化云数智",
        "url": "https://d.sinochemitc.com",
        "category": "化工企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "sinopec_esign": {
        "name": "石化e签",
        "url": "https://esign.sinopec.com",
        "category": "能源/石油",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "impc": {
        "name": "内蒙古电力",
        "url": "https://ecp.impc.com.cn:21002/",
        "category": "电网公司",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "dingdangmro": {
        "name": "叮当工业品招标平台",
        "url": "https://www.dingdangmro.com/",
        "category": "第三方平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "btsteel": {
        "name": "包钢电子采购交易平台",
        "url": "http://ep.btsteel.com/",
        "category": "钢铁企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cg95306": {
        "name": "国铁采购平台",
        "url": "https://cg.95306.cn/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "sxtba": {
        "name": "山西招标采购服务平台",
        "url": "https://www.sxtba.com/",
        "category": "公共资源平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "bcegc": {
        "name": "北京建工",
        "url": "http://chunshan.bcegc.com/",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cnmc": {
        "name": "中国有色矿业集团有限公司",
        "url": "http://ecp.cnmc.com.cn/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "ebuycsemc": {
        "name": "中船集团采购电子商务平台",
        "url": "https://www.ebuycsemc.com/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "hebpr": {
        "name": "河北省公共资源交易平台",
        "url": "http://publicservice.hebpr.gov.cn/",
        "category": "公共资源平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "tengxiangjiangong": {
        "name": "腾祥建工",
        "url": "http://tengxiangjiangong.com/",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cmcc": {
        "name": "中国移动",
        "url": "https://b2b.10086.cn/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "avicbid": {
        "name": "中航招标网",
        "url": "https://www.avicbid.com/",
        "category": "第三方平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cebpubservice2": {
        "name": "中国招标投标公共服务平台（官网）",
        "url": "http://www.cebpubservice.com/",
        "category": "通用招标平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "jingye": {
        "name": "敬业集团电子招标平台",
        "url": "https://dzzb.hbjyjt.com/",
        "category": "钢铁企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "ispacechina": {
        "name": "航天电子",
        "url": "https://www.ispacechina.com/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "cnncecp": {
        "name": "中核",
        "url": "https://www.cnncecp.com/",
        "category": "央企",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "xincheng": {
        "name": "新城控股供应商平台",
        "url": "https://oasis-sp.xincheng.com/",
        "category": "地产企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "zchzb": {
        "name": "中采惠招电子招投标交易平台",
        "url": "http://www.zchzb.com/",
        "category": "第三方平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "tjcj": {
        "name": "天津城建控股",
        "url": "https://tjcj.srm.glodon.com",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "flint_sgcc": {
        "name": "山东易书",
        "url": "http://www.flint.sd.sgcc.com.cn/",
        "category": "电网公司",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "juhua": {
        "name": "巨化",
        "url": "https://juhua.ccccnet.com/",
        "category": "化工企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "bucg": {
        "name": "北京城建",
        "url": "http://i.bucg.com/",
        "category": "建筑企业",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "zjycgzx_hongchuang": {
        "name": "浙江云采购平台",
        "url": "https://hongchuang.zjycgzx.com/",
        "category": "第三方平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
    "suex": {
        "name": "苏州交易集团阳光采购管理系统",
        "url": "https://ygcg.suex.com.cn/",
        "category": "公共资源平台",
        "crawler_type": "custom",
        "enabled_by_default": False,
        "timeout": None,
        "max_retries": None,
        "request_delay": None,
        "headers": None,
        "use_selenium": None,
    },
}


# =============================================================================
# 导出 API
# =============================================================================

def get_sites() -> Dict[str, Dict[str, Any]]:
    """获取所有网站定义"""
    return dict(SITES)


def get_site_config(key: str) -> Optional[Dict[str, Any]]:
    """获取单个网站的配置"""
    return SITES.get(key)


def get_categories() -> Dict[str, str]:
    """获取所有分类定义"""
    return dict(SITE_CATEGORIES)


def get_sites_by_category() -> Dict[str, List[Dict[str, Any]]]:
    """按分类分组返回网站列表
    
    Returns:
        {分类名: [{key, name, url, ...}, ...]}
    """
    result: Dict[str, List[Dict[str, Any]]] = {cat: [] for cat in SITE_CATEGORIES}
    for key, cfg in SITES.items():
        cat = cfg.get("category", "其他")
        if cat not in result:
            result[cat] = []
        item = dict(cfg)
        item["key"] = key
        result[cat].append(item)
    return result


def get_default_enabled_sites() -> List[str]:
    """获取默认启用的网站 key 列表"""
    return [k for k, v in SITES.items() if v.get("enabled_by_default", False)]


def get_all_site_keys() -> List[str]:
    """获取所有支持的网站 key 列表"""
    return list(SITES.keys())


def validate_enabled_sites(enabled_sites: List[str]) -> tuple[List[str], List[str]]:
    """校验并过滤无效的站点配置
    
    Returns:
        (有效列表, 无效列表)
    """
    all_keys = set(SITES.keys())
    valid = [k for k in enabled_sites if k in all_keys]
    invalid = [k for k in enabled_sites if k not in all_keys]
    return valid, invalid


# =============================================================================
# 向后兼容 API（逐步淘汰）
# =============================================================================

def get_builtin_crawler_sites() -> Dict[str, Dict[str, str]]:
    """获取有专用爬虫支持的网站（兼容旧接口）"""
    return {
        k: {"name": v["name"], "url": v["url"]}
        for k, v in SITES.items()
        if v.get("crawler_type") == "builtin"
    }


def get_default_sites() -> Dict[str, Dict[str, str]]:
    """获取默认的内置网站列表（兼容旧接口）"""
    return {
        k: {"name": v["name"], "url": v["url"]}
        for k, v in SITES.items()
    }
